export var ROUTES = [
    '/',
    '/flats/plan',
    '/flats/plan/house/:house',
    '/flats/plan/house/:house/section/:section/floor/:floor',
    '/flats/plan/house/:house/section/:section/floor/:floor/apartment/:apartment',
    '/flats/search',
    '/favorites',
    '/dynamics/build/:year/:month',
    '/dynamics/built',
    '/dynamics/edit_news/:id',
    '/dynamics/news-shares/:indexNum',
    '/dynamics/news-shares/:indexNum/:id',
    '/conditions/installment',
    '/conditions/credit',
    '/shares',
    '/shares/list/:index',
    '/shares/list/:index/:id',
    '/shares/edit/:id',
    '/news-shares/:id',
    // '/about/plan',
    // '/about/builder',
    '/about/documentations',
    '/contact',
];
//# sourceMappingURL=rendering.routes.js.map